### ISSUE TITLE
Implement qemu guest filesystem fsfreeze/unfreeze

### ISSUE THREAD

**Issue by damdo** [bradfitz/qemu-guest-kragent#2]
Hi @bradfitz, thanks a lot for your work on this.

I'm using `qemu-guest-kragent` in my gokrazy VMs onProxmox/qemu and now I'm looking into creating snapshots and perform migrations of those VMs.

Unfortunately while trying to move them around via Proxmox Migrate, the migration process gets stuck while freezing the guest filesystem.

Looking at the qemu-guest-kragent logs, things seem to be getting stuck due to:
```
2024/05/04 23:33:06 Unhandled command "guest-fsfreeze-freeze"
2024/05/05 00:33:07 Unhandled command "guest-fsfreeze-thaw"
```

I wonder if we could try and give it a shot at implementing them (and `guest-fsfreeze-status` as a bonus) in the main kragent switch/case:
https://github.com/bradfitz/qemu-guest-kragent/blob/a9f5e8a3ad8db09bbf9efb2825cea9445871c7c8/kragent.go#L58

Thinking about it, are we supposed to invoke `fsfreeze` against the Filesystems?
I know the root gokrazy filesystems is read-only, but there are also other RW FS.

I found some prior art on fsfreeze in another Go guest-agent [here](https://github.com/0xef53/phoenix-guest-agent/blob/ef58ba04772a45ecda32438db9ca75b2ae460736/main.go#L196) and [here](https://github.com/0xef53/phoenix-guest-agent/blob/master/fsfreeze.go), maybe this can help us.

cc. @stapelberg 
Who might have thoughts on how to handle this on the OS side :)

**Comment by stapelberg** [comment]
TIL about fsfreeze (never needed it before) :) Yeah, the root fs is read-only, so that can be ignored. I think you just need to traverse the /proc/self/mountinfo file to discover mounted file systems, then do an fsfreeze syscall on them.

**Comment by damdo** [comment]
> never needed it before

Me neither :)

>  I think you just need to traverse the /proc/self/mountinfo file to discover mounted file systems, then do an fsfreeze syscall on them.

Done it in #3
